### ISSUE TITLE
RF_test_agent for bare metal in C disappeared

### ISSUE THREAD

**Issue by SwissKnife64** [SiliconLabs/wfx-common-tools#2]
Last week I followed this link: [RF_test_agent](https://github.com/SiliconLabs/wfx-fullMAC-tools/tree/master/Tools/RF_test_agent)
There was a folder containing the RF test agent for bare metal implementation in C. **The folder and the code has disappeared.**
The link is still present at the bottom of the page [WFX RF Testing](https://github.com/SiliconLabs/wfx-common-tools/tree/master/test-feature)

Please restore these folders as quick as possible or correct the link to the new location. 
_I need the files to implement testing. There are only some days left till the reserved day in the testing lab!_

**Comment by SwissKnife64** [comment]
After some clicking through the different WFX repositories I have found the new location of the [RF Test Agent](https://github.com/SiliconLabs/wfx-fullMAC-tools/tree/main/wifi_cli_micriumos/rf_test_agent), as a part of the micriumos CLI.
Please update/add the link to this bare metal implementation on the [WFX RF Testing](https://github.com/SiliconLabs/wfx-common-tools/tree/master/test-feature) page.

**Comment by silabs-JulienT** [comment]
Thanks for the report. Indeed, with the newly added Simplicity Studio 5 support, the former repository content has been transferred to the "wifi_examples_ss4" branch. We will update the documentation accordingly. You can still use the Simplity Studio 4 RF test agent. In Simplicity Studio 5, the RF test agent is now part of the wifi_cli project. The information can be found [here](https://github.com/SiliconLabs/wfx-fullMAC-tools/tree/main/wifi_cli_micriumos/rf_test_agent).

Regards,
Julien
