### ISSUE TITLE
Compatibility with upstream driver

### ISSUE THREAD

**Issue by sl8vz** [SiliconLabs/wfx-common-tools#7]
Hi,
Upstream WFX driver requires PDS in TLV format and these testing tools are not compatible.
Is it planned to release an update ?

Thanks,
Sebastien

**Comment by MarcDorval** [comment]
Hi Sebastien,

Can you please elaborate what you mean by 'not compatible'?
The tools generate text strings which are sent to the wfx_test_agent (https://github.com/SiliconLabs/wfx-linux-tools/tree/SD5/test-feature).
It's been working for years.

Regards,
Marc

**Comment by sl8vz** [comment]
Hi Marc,
The in-tree Linux driver only supports PDS in binary TLV format.
These test tools do not support this format and the wfx driver complains:
```
[ 2557.946049] wfx-spi spi0.0: PDS: malformed file (legacy format?)
[ 2617.880753] wfx-spi spi0.0: PDS: malformed file (legacy format?)
[ 2619.920132] wfx-spi spi0.0: PDS: malformed file (legacy format?)
[ 2621.492239] wfx-spi spi0.0: PDS: malformed file (legacy format?)
```
See:
https://community.silabs.com/s/question/0D58Y00009gyqZeSAI/how-to-generate-non-legacy-pds-for-upstream-linux-wfx-driver

Regards,
Sebastien

**Comment by MarcDorval** [comment]
Hi Sebastien,

What is your flow?
How did you generate your `/lib/firmware/wf200.pds` file?

If this one is accepted (I believe it is, because you have a running WFX200), the same encoding (i.e. an identical pds_compress) should be used for RF tests.

The one used to compress `/lib/firmware/wf200.pds` on a RPi is `/usr/local/bin/pds_compress`
The one used to compress PDS strings for RF tests on a RPi is `/home/pi/siliconlabs/wfx-common-tools/test-feature/pds_compress.py`

You should get identical results using an identical PDS file in human-readable format for both.

Regards,
Marc

**Comment by sl8vz** [comment]
Hi Marc,

> What is your flow?
> How did you generate your /lib/firmware/wf200.pds file?

Using pds_compress from `wfx-linux-tools` with `--out=tlv` option.

The `wfx-common-tools/test-feature` use a `pds_compress` which indeed doesn't have this option.
I was more asking if this is something that you were planning to update but I can provide a MR so it's working out of the box for in-tree driver.

Thx,
Sebastien

**Comment by MarcDorval** [comment]
I'll update /home/pi/siliconlabs/wfx-common-tools/test-feature/pds_compress.py as well.
The RF test tool may need to be locally updated to set the `--out=tlv` option when calling `compress_string()`. If we change this it would not work if not using the upstream driver.

**Comment by MarcDorval** [comment]
I updated https://github.com/SiliconLabs/wfx-common-tools.
Users of the upstream wfx driver will need to set
`pds_env['required_options'] = "--out=tlv"`
In [wfx_test_target.py](https://github.com/SiliconLabs/wfx-common-tools/blob/master/test-feature/wfx_test_target.py#L25)

**Comment by MarcDorval** [comment]
Sebastien,

Can you please check if my changes are working?
I don't have the entire setup ready anymore.

Marc

**Comment by sl8vz** [comment]
Hi Marc,
There are a few minor issues, I'll post a MR tomorrow.

Thx

**Comment by sl8vz** [comment]
Closing. Using #8 allows testing the upstream driver
